### ISSUE TITLE
인게임 (2차) - 컴포넌트

### ISSUE THREAD

**Issue by kugorang** [motionbeat/MOTION-BEAT-Frontend#37]
- [x] 다른 유저의 노트는 반투명 처리
- [x] 인게임 컴포넌트 구현
  - [x] 점수
  - [x] 판정 이펙트
  - [x] 웹캠 프레임
  - [x] 아웃풋 : 자신에게 할당된 악보 반응
 
- [x] 리듬게임 플로우 구현
  - [x] 기본 데이터 로딩
  - [x] 노래 재생
  - [x] 더미데이터에 따른 노트 등장
  - [x] 노트 판정
  - [x] 판정 시 점수 증가

- [x] #40 동기화

**Comment by AnyTHIW** [comment]
- [ ] 노트 구현 문제
- - [ ] 키 연속 입력 시 노트 다중판정문제

**Comment by AnyTHIW** [comment]
release 0.2.0 출시 즉시 닫을 예정

**Comment by kugorang** [comment]
* 작업자가 작업 완료 후 branch 삭제 및 Issue Closed 필요
